{
  writers,
  python3Packages,
}:

writers.writePython3Bin "bookletify" {
  libraries = [
    python3Packages.pypdf
  ];
  flakeIgnore = [
    "E265" # Ignore error generated by shebang (block comment should start with '# ')
    "E501" # Ignore 'line too long' errors
  ];
} (builtins.readFile ./bookletify)
